
spring:
  application:
    name: mycat-consumer
  redis:
      database: 1
      hostName: 10.10.203.13
      port: 6379
      password: Jht123456
      encode: utf-8
      pool:
        maxIdle: 300
        maxTotal: 600
        timeBetweenEvictionRunsMillis: 30000
        minEvictableIdleTimeMillis: 30000
        testOnBorrow: true
      key_prefix: test
      
server:
  port: 6001
 
 #Eureka config for mycat
eureka:
    instance:
        statusPageUrlPath: /actuator/info  #服务信息
        healthCheckUrlPath: /actuator/health  #服务心跳
        hostname: 10.101.90.220  #服务注册中心ip
        preferIpAddress: true  #是否使用ip注册到服务中心
        instance-id: 10.101.90.220:${server.port}  #当前服务的访问地址
    client:
        enabled: true
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#admin config
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
info:
  version: 1.0
