spring:
  application:
    name: mycat-getaway
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
      - id: 163                     #网关路由到网易官网
        uri: http://www.163.com/
        predicates:
          - Path=/163/**
      - id: mycat-consumer
        uri: lb://mycat-consumer
        order: 8000
        predicates:
          - Path=/api/**
        filters:
          - SwaggerHeaderFilter
          - StripPrefix=1
      - id: MYCAT-PROVIDER
        uri: lb://MYCAT-PROVIDER
        order: 8001
        predicates:
          - Path=/api/testProvider/**
        filters:
          - SwaggerHeaderFilter
          - StripPrefix=2
      
server:
  port: 5001
 
logging:
  level:
    org.springframework.cloud.gateway: debug
#    org.springframework.http.server.reactive: debug
#    org.springframework.web.reactive: debug
#    reactor.ipc.netty: debug
 
 #Eureka config for mycat
eureka:
    instance:
        statusPageUrlPath: /actuator/info  #服务信息
        healthCheckUrlPath: /actuator/health  #服务心跳
        hostname: 10.101.90.220  #服务注册中心ip
        preferIpAddress: true  #是否使用ip注册到服务中心
        instance-id: 10.101.90.220:${server.port}  #当前服务的访问地址
    client:
        enabled: true
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true

#admin config
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
info:
  version: 1.0
